build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false

coding_style:
    php:
        indentation:
            general:
                size: 2


tools:
    php_cs_fixer:
        config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
