language: php
php:
  - '5.6'
  - '7.1'

before_script:
  - cp .env.travis .env
  - mysql -e 'create database fakultet;'
  - composer self-update
  - composer require --dev phpunit/phpunit ^6.5
  #- composer install --no-interaction

script:
  - vendor/bin/phpunit
