language: php
php:
  - '7.1'

before_script:
  - cp .env.travis .env
  - mysql -e 'create database fakultet;'
  - composer self-update
  - composer require --dev phpunit/phpunit ^6.5
  #- composer install --no-interaction

script:
  - vendor/bin/phpunit --debug --bootstrap vendor/autoload.php tests/
  
deploy:
  provider: heroku
  api_key:
    secure: "e9fcfc33-cdd3-493d-9f17-c04b3a0b399f"
  app: phpdev2018